### ISSUE TITLE
Wrong behavior on referenceMode = 'id' / multiple = true and form update

### ISSUE THREAD

**Issue by BioSin** [Innqube/ng2-iq-select2#17]
Hello, when I use referenceMode = 'id' / multiple = true and trying to set value on the form your component Duplicates selected options, for instance:

```
BEFORE:
FormState: { country_id: [1,2] }
Visible Options: country1, country2

Call form.setValue([1,2]) <- For instance I click submit button, send data, receive updated model and assign it to form state

AFTER:
FormState: { country_id: [1,2] } <- Form state still the same
Visible Options: country1, country2, country1, country2
```

It because in handleMultipleWithIds you don't check already selected values.
My proposal to change method to:

```
private handleMultipleWithIds(selectedValues: any) {
        if (selectedValues !== undefined && this.selectedProvider !== undefined) {
            this.selectedProvider(selectedValues).subscribe((items: T[]) => {
              let ids = this.getSelectedIds();

              items.map(this.iqSelect2ItemAdapter)
                .filter((el) => ids.indexOf(el.id) === -1)
                .forEach((item) => this.selectedItems.push(item));
            });
        }
    }
```

BTW: thank you for that component.

**Comment by BioSin** [comment]
@diegofsza You solution of described issue isn't correct. 

Because you still appending duplicated items to `this.selectedItems` array, issue in this place, not in `selectedValues` argument, which may have non-unique value. 
There are 2 solutions:
1) Additional check of uniquest of `this.selectedValues`, as it was in my implementation
2) Replace `this.selectedValues.push({newValue})` to `this.selectedValues = {newValue}`

**Comment by diegofsza** [comment]
Ok, I did not understeand it well the first time. I think this is fixed now. Give it a try please. Regards.

**Comment by diegofsza** [comment]
I think I will switch to the 2nd suggested implementation. With the first one it allows you to load values into the component that will remain after doing a `form.patchValue({..})`. I don't think that is an expected behavior.

**Comment by BioSin** [comment]
If it's not brake any other logic, it will be nice. I thought what you did it for some reason (append items, instead of assign) because writeValue give us *current* form value. Thank you for quick response!
