### ISSUE TITLE
Angular 4+ Support

### ISSUE THREAD

**Issue by chrisbmoore** [Innqube/ng2-iq-select2#28]
Any chance this can be updated to work with Angular 4? Or an Angular 4 fork can be made?

**Comment by diegofsza** [comment]
Hi, I'm currently using it in Angular 4 projects. Did you have problems when trying to use it?

**Comment by chrisbmoore** [comment]
I have some errors when installing via npm because I have Angular 4.0.2 installed.

+-- UNMET PEER DEPENDENCY @angular/common@4.0.2
+-- UNMET PEER DEPENDENCY @angular/core@4.0.2
+-- UNMET PEER DEPENDENCY @angular/platform-browser@4.0.2
+-- ng2-iq-select2@4.2.4
`-- UNMET PEER DEPENDENCY zone.js@0.8.5

npm WARN ng2-iq-select2@4.2.4 requires a peer of @angular/common@^2.2.3 but none was installed.
npm WARN ng2-iq-select2@4.2.4 requires a peer of @angular/core@^2.2.3 but none was installed.
npm WARN ng2-iq-select2@4.2.4 requires a peer of @angular/platform-browser@^2.2.3 but none was installed.
npm WARN ng2-iq-select2@4.2.4 requires a peer of zone.js@^0.7.6 but none was installed.

I assumed it's because your package.json doesn't include Angular 4 in the semver ranges. Possibly change all angular peer dependencies ">=2.4.0" so it includes latest Angular 2 and future Angular versions. 

I'm not sure why it's complaining about needing 2.2.3 instead of 2.4.0. Is there an older version on npm than github? Or does one of your other dependencies restrict the Angular version? Correct me if I'm misunderstanding something.

**Edit** Oh I think the 2.2.3 is coming from your nested package.json. 

"peerDependencies": {
    "@angular/common": "^2.2.3",
    "@angular/core": "^2.2.3",
    "@angular/platform-browser": "^2.2.3",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.7.6"
  },

**Comment by diegofsza** [comment]
I see. Will try applying your suggestion as soon as I can. Anyway, in the mean time I think you can ignore the warnings and use the component normally. Let me know if this is not possible or causes troubles I'm not seeing right now.

**Comment by diegofsza** [comment]
Applying your suggestion fixed the warning messages. Thanks.

**Comment by chrisbmoore** [comment]
Cool, it should be fine if you updated angular to the latest 4.X version and it builds and passes all your tests. If angular happens to break your code in the far future, you could change it to a range instead. Example: (>=2.2.3 <5.0.0). I think that would work, but I'm no expert.
