### ISSUE TITLE
ERROR in IqSelect2Module is not an NgModule

### ISSUE THREAD

**Issue by valeriy-maslov** [Innqube/ng2-iq-select2#33]
I have this setup:
angular: 2.3.1
angular-cli: 1.0.0-rc.4 (also tried 1.0.1, same thing)
ng2-iq-select2: 4.2.7

```ERROR in IqSelect2Module is not an NgModule``` occurs during ```ng serve```, ```ng test``` and ```ng build``` (with any parameters).

Can you fix that? Let me know if you need some extra information from me. Thanks

**Comment by diegofsza** [comment]
Sorry, I know you opened this issue while ago and I totally missed to answer you. I'm looking into every single issue in order to close them. Are you still trying to use the component? Did you manage to get it working?
