### ISSUE TITLE
Selected item is permanently removed from list

### ISSUE THREAD

**Issue by mikaelmattsson** [Innqube/ng2-iq-select2#34]
Selected item is permanently removed from list and can not be reselected if unselected.

I commented about this [here](https://github.com/Innqube/ng2-iq-select2/commit/4c6488895781f3b74428b76514247dcd9d59d68e).

`filterLocalData` already does the trick of removing the selected item (not permanently).
`adaptItems` should not do this.

**Comment by diegofsza** [comment]
Well, I think now the issue is gone! (version 4.2.8)
