### ISSUE TITLE
remove source files from npm package

### ISSUE THREAD

**Issue by saithis** [Innqube/ng2-iq-select2#39]
Currently the npm package contains the typescript source files. This can cause a problem, if someone using ng2-iq-select2 activates some strict compiler options, that ng2-iq-select2 doesn't fulfill. Then typescript will report an error in node_modules/ng2-iq-select2/... and won't compile.

I tried to fix this issue in this branch: https://github.com/saithis/ng2-iq-select2/commits/publish_script
But my problem is, that this only works with inline styles and template. Would it be ok for you to inline them? Otherwise angular2-inline-template-style could maybe be a solution.

**Comment by diegofsza** [comment]
I think that if that is necessary to have a more robust component, it will be no problem. I would rather like to keep them separated, though. Do you think that organizing the `component-wrapper` folder based on [this library generator](https://github.com/jvandemo/generator-angular2-libraryIqSelect2ResultsComponent) for example, could help? It seems that there is a script that inlines resources when building the library. This is just to evaluate another possibility before inlining everything.

**Comment by saithis** [comment]
I did some research yesterday and it seems, that publishing a library that is compatible with almost everything is really hard. There is a [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview), but generating it is a pain in the ass.


* angular-cli: Will only support library development when it is based on [angular devkit](https://github.com/angular/devkit), which seems to be with version 2. But angular devkit is still in development and it will take at least a year, till it will be released.

* [angular-quickstart-lib](https://github.com/filipesilva/angular-quickstart-lib): Is the one a member of the angular-cli team [recommended](https://github.com/angular/angular-cli/issues/6510#issuecomment-305092643), but the demo app is based on system.js and this makes publishing to github pages difficult (see issue [here](https://github.com/filipesilva/angular-quickstart-lib/issues/26)).

* [angular-library-starter](https://github.com/shlomiassaf/angular-library-starter): Looks good to me, but didn't try it out yet.

I took a quick look at the one you found and I'm not sure if it properly supports demo apps for github pages.

**Comment by diegofsza** [comment]
Github pages will be a nice feature. Currently, this library is not using it properly. The demo linked in the docs is another repo and it is really outdated. It is something I had pending to do... to update the demo and integrate it properly in this repo.

Anyway, meanwhile I think we could just include some gifs or images showing the behavior of the component and remove the live demo. That way it will be easier to use any of the solutions discussed previously. The 3rd option you mentioned looks great, but I haven't used it neither.

**Comment by saithis** [comment]
Another 2 possibilities would be [angular-librarian](https://github.com/gonzofish/angular-librarian) and [ng-packagr](https://github.com/dherges/ng-packagr). The advantage of the 2 is, that they are cli tools like angular-cli which makes updates easier. They seem to have fewer features than angular-library-starter for now, but easier updates and possibily easier integration could make up for that.

**Comment by saithis** [comment]
- angular-librarian doesn't output the Angular Package Format
- ng-packagr [doesn't support unit testing yet](https://github.com/dherges/ng-packagr/issues/5)
- angular-library-starter: I tried to integrate it with ng2-iq-select2 and I think every update of angular-library-starter would be a pain in the ass, because you can't just copy and paste the files, you have to diff them and apply each change manually :/

So I just made a PR which removes the source files from the npm package for now. I think its better to wait until someone specifically asks for a umd bundle/etc. or the proccess to generate the Angular Package Format gets easier and implement it then.
