### ISSUE TITLE
allowClear option

### ISSUE THREAD

**Issue by achimha** [Innqube/ng2-iq-select2#44]
Select2 has an option `allowClear` to choose whether the user should be allowed to unselect a result without selecting a new one.

Can this be achieved with the component?

**Comment by diegofsza** [comment]
Yes. It is the default behavior of the component. It allows you to remove the selection on a item by item basis (in case you are using the behavior to select multiple items).

What you can not do, is to hide the remove button. It will hide automatically when the component is disabled, though.
