### ISSUE TITLE
Request for full source code for demo

### ISSUE THREAD

**Issue by yskeat** [Innqube/ng2-iq-select2#45]
I am using Angular CLI version 1.0.2 and Angular Core version 4.3.6. 
My problem is I can get it work based on your example usage in README.md.
It did not return any error.

It is possible to share full source code for demo at https://innqube.github.io/ng2-iq-select2-demo/
?

**Comment by diegofsza** [comment]
Hi, that demo is pretty outdated. It is in the following repo if you would like to take a look: https://github.com/Innqube/ng2-iq-select2-demo. Anyways, I repeat, I don't think it will be helpful.

If you share your code, I would be glad to help you.
