### ISSUE TITLE
placeholder dissapears when form is reset 

### ISSUE THREAD

**Issue by wautersj** [Innqube/ng2-iq-select2#46]
I'm using the select in combination with the formControlName inside of a FormGroup.
When the Form is initialised the placeholder shows. But when I run the same command, to reset the form values, the placeholder is blanked.

It seems as when the input is cleared, the .hideable class remains present on the input.
Resulting in the input (and its placeholder) not beïng visible.

**Comment by diegofsza** [comment]
This will be fixed in the next release!
