### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by Hesesses** [Innqube/ng2-iq-select2#49]
Does this work with the latest bootstrap 4 beta?

**Comment by diegofsza** [comment]
It will work, but it probably won't fit precisely with the others form controls. Icons won't be available neither. The component has several classes you may customize to try to fit your needs, but I haven't tested them by myself in order to play nicely with bootstrap 4.

**Comment by egesu** [comment]
@Hesesses I added the css below and it doesn't look so bad now. At least the height is same as other inputs.

```
// ng2-iq-select2 fixes for bootstrap 4
.select2-selection-container {
  min-height: 38px !important;
}
```

**Comment by diegofsza** [comment]
ng2-iq-select2@8.0.0 supports bootstrap 4 now
