### ISSUE TITLE
Entity mode, selected value 

### ISSUE THREAD

**Issue by BioSin** [Innqube/ng2-iq-select2#9]
Hello, when we set "Entity mode" with single value(maybe with multiple too), and pick a value, in form control I see entity, not IqSelect2Item.
In this case when we hide, and then show input again(for instance *ngIf), component don't show expected selected value(because it's value ENTITY, not IqSelect2Item), but in form control I see it.

For now I made a hack in my component, onSelect event set form value again.
`this.form.get([i, 'country_id']).setValue($event);`

**Comment by diegofsza** [comment]
Hmm... I suppose it will be necessary to pass the component another function with the following signature: `(entity: any) => IqSelect2Item`
That way it should be able not only to handle the issue you reported, but also, it will feel more intuitive when loading data into the formGroup, as you won't have to worry to convert your entity to an IqSelect2Item explicitly.

**Comment by diegofsza** [comment]
Take a look at version 3.0.0. You will have to modify your current code, but the component feels much more comfortable to use now.

**Comment by BioSin** [comment]
@diegofsza yes, it works great! Thank you!
